//created on: Jul 1, 2014
package RuleAsma
 
import pt.manchester.logic.Areas.*;
import pt.manchester.logic.Opcoes.*;
import java.util.Scanner;

rule "Rule Asma - Inicial"
    when
        area : AreaAsma(escalaActual == Area.EscalaTriagem.etSemEscala);
    then
        System.out.println(area.getClass().getSimpleName()+"\n");
        
        // O fluxograma inicia sempre do caso mais crítico/emergente para o caso menos urgente        
        System.out.println("Escolha uma das opções:");
        int i = 0;
        for (; i < area.getOpcoesVermelhas().size(); i++)
        {
        	System.out.println(i+": "+area.getOpcoesVermelhas().get(i).getCaption() + "?");	
        }
        System.out.println(i+": Nenhuma");	        
        
        Scanner input = new Scanner(System.in);
		int opcao = input.nextInt();
		
		if (opcao == i)
			area.setEscalaActual(Area.EscalaTriagem.etVermelho);
		else 		
			area.setEscalaActual(Area.EscalaTriagem.etLaranja);
        
        update(area);
end

rule "Rule Asma - Resultado"
    when
        area : AreaAsma(escalaActual == Area.EscalaTriagem.etVermelho);
    then
    	System.out.println("Triagem efectuada");
    	retract(area);
end
