package RuleDiabetes

import pt.manchester.ui.text.*;
import pt.manchester.logic.*;
import pt.manchester.logic.Areas.*;

rule "Rule Diabetes - Inicial/Vermelho"
    when
        area : AreaDiabetes(escalaActual == EscalaTriagem.etSemEscala);
    then
        Comandos comandos = new Comandos(area);
        int opcao = comandos.showOpcoes();
        int opcaoNenhum = comandos.getOpcoesCount();

		if (opcao == opcaoNenhum)
		{
            area.setEscalaActual(EscalaTriagem.etLaranja);
            update(area);
        }
		else
		{
            area.setEscalaActual(EscalaTriagem.etVermelho);
            insert(new Resultado(area));
            retract(area);
        }
end

rule "Rule Diabetes - Laranja"
    when
        area : AreaDiabetes(escalaActual == EscalaTriagem.etLaranja);
    then
        Comandos comandos = new Comandos(area);
        int opcao = comandos.showOpcoes();
        int opcaoNenhum = comandos.getOpcoesCount();

        if (opcao == opcaoNenhum)
        {
            area.setEscalaActual(EscalaTriagem.etAmarelo);
            update(area);
        }
        else
        {
            insert(new Resultado(area));
            retract(area);
        }
end

rule "Rule Diabetes - Amarelo"
    when
        area : AreaDiabetes(escalaActual == EscalaTriagem.etAmarelo);
    then
        Comandos comandos = new Comandos(area);
        int opcao = comandos.showOpcoes();
        int opcaoNenhum = comandos.getOpcoesCount();

        if (opcao == opcaoNenhum)
        {
            area.setEscalaActual(EscalaTriagem.etVerde);
            update(area);
        }
        else
        {
            insert(new Resultado(area));
            retract(area);
        }
end

rule "Rule Diabetes - Verde"
    when
        area : AreaDiabetes(escalaActual == EscalaTriagem.etVerde);
    then
	    insert(new Resultado(area));
	    retract(area);
end
