package RuleFeridas

import pt.manchester.ui.text.*;
import pt.manchester.logic.*;
import pt.manchester.logic.Areas.*;

rule "Rule Feridas - Inicial/Vermelho"
salience 100
    when
        area : AreaFeridas(escalaActual == EscalaTriagem.etSemEscala);
    then
        Comandos comandos = new Comandos(area);
        int opcao = comandos.showOpcoes();
        int opcaoNenhum = comandos.getOpcoesCount();

		if (opcao == opcaoNenhum)
		{
            area.setEscalaActual(EscalaTriagem.etLaranja);
            update(area);
        }
		else
		{
            area.setEscalaActual(EscalaTriagem.etVermelho);
            insert(new Resultado(area));
            retract(area);
        }
end

rule "Rule Feridas - Laranja"
salience 75
    when
        area : AreaFeridas(escalaActual == EscalaTriagem.etLaranja);
    then
        Comandos comandos = new Comandos(area);
        int opcao = comandos.showOpcoes();
        int opcaoNenhum = comandos.getOpcoesCount();

        if (opcao == opcaoNenhum)
        {
            area.setEscalaActual(EscalaTriagem.etAmarelo);
            update(area);
        }
        else
        {
            insert(new Resultado(area));
            retract(area);
        }
end

rule "Rule Feridas - Amarelo"
salience 50
    when
        area : AreaFeridas(escalaActual == EscalaTriagem.etAmarelo);
    then
        Comandos comandos = new Comandos(area);
        int opcao = comandos.showOpcoes();
        int opcaoNenhum = comandos.getOpcoesCount();

        if (opcao == opcaoNenhum)
        {
            area.setEscalaActual(EscalaTriagem.etVerde);
            update(area);
        }
        else
        {
            insert(new Resultado(area));
            retract(area);
        }
end

rule "Rule Feridas - Verde"
salience 25
    when
        area : AreaFeridas(escalaActual == EscalaTriagem.etVerde);
    then
	    insert(new Resultado(area));
	    retract(area);
end
